#Project: Deep Learning Classifier to estimate the probability of future metastasis from Breast Primary Tumor WES data
#@feBueno fernando.bueno.gutierrez@usal.es August-2020

#Script to input Breast Primary Tumor WES data from multiple data sources into in-house BRCAmet_classifier.py
#The script provides different options to carry variable selection: selection of the mutation positions that may be better metastasis predictors 
#Files generated by this script can also work as input for GDL (https://www.nature.com/articles/s41598-019-53989-3) with little modifications

#REQUIRES
#BRCAmet_funs1.R
#BRCAmet_funs2.R

#OUTPUT: The 6 input .txt files required by BRCAmet_classifier.py:
  #./metClassiInputByBRCAmet/Xtr.txt   #train predictors
  #./metClassiInputByBRCAmet/Xv.txt    #validation predictors
  #./metClassiInputByBRCAmet/ytr.txt   #train labels
  #./metClassiInputByBRCAmet/yv.txt    #validation labels
  #./metClassiInputByBRCAmet/Xte.txt   #test predictors
  #./metClassiInputByBRCAmet/yte.txt   #test labels

setwd("/home/febueno/Documents/BRCAmetProject")
source("./BRCAmet/scripts/BRCAmet_funs1.R")
saveMutationData_fun(excludeNgeV8_b=F)#call this function if mut_df does not exists
mut_df=read.table("./BRCAmet/data/WES/myTransformedData/ready_df/mut_hg38_df.txt",header=T)
remNeg2balance_b=T;nSamplesBalancedTest_i=100;percVal_n=0.2;MutReductionMethod_c="createMpWindows";extraParameter_i=1000
saveTrainTestMetClassiInput(mut_df,remNeg2balance_b=T,nSamplesBalancedTest_i=100,percVal_n=0.2,MutReductionMethod_c="createMpWindows",extraParameter_i=1000)
saveTrainTestMetClassiInput(mut_df,remNeg2balance_b=T,nSamplesBalancedTest_i=100,percVal_n=0.2,MutReductionMethod_c="groupMpInGenes",extraParameter_i= NA)





